### ISSUE TITLE
Tutorials are non functional due to online compiler error

### ISSUE THREAD

**Issue by mleadbeater** [chrberger/libcluon#15]
The online compiler seems to be giving an error, see below. As far as I can tell wandbox.org is operational.

`ReferenceError: twttr is not defined
    at https://wandbox.org/build/_shared/chunk-HWTQ5KW5.js:104:29713
    at Gf (https://wandbox.org/build/_shared/chunk-2LKANNDY.js:9:6560)
    at L.unstable_runWithPriority (https://wandbox.org/build/_shared/chunk-2LKANNDY.js:1:4026)
    at rn (https://wandbox.org/build/_shared/chunk-2LKANNDY.js:5:38448)
    at Xe (https://wandbox.org/build/_shared/chunk-2LKANNDY.js:9:6029)
    at yi (https://wandbox.org/build/_shared/chunk-2LKANNDY.js:7:10750)
    at https://wandbox.org/build/_shared/chunk-2LKANNDY.js:5:38670
    at L.unstable_runWithPriority (https://wandbox.org/build/_shared/chunk-2LKANNDY.js:1:4026)
    at rn (https://wandbox.org/build/_shared/chunk-2LKANNDY.js:5:38448)
    at Cs (https://wandbox.org/build/_shared/chunk-2LKANNDY.js:5:38616)`

**Comment by chrberger** [comment]
I looked at it from my end and it worked. Maybe, you have a blocking filter on some embedded scripts at wandbox in place?

**Comment by mleadbeater** [comment]
Yeah works for me too. Apologies.
